version: "3"

services:

  runtime-setup:
    image: swift-nio-extras:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"

  documentation-check:
    image: swift-nio-extras:22.04-5.7

  test:
    image: swift-nio-extras:22.04-5.7

  shell:
    image: swift-nio-extras:22.04-5.7
